set(MAINTAINER_NAME "Noah Reeder <noahreederatc@gmail.com>")
set(PROJECT_VERSION_MAJOR 0)
set(PROJECT_VERSION_MINOR 0)
set(PROJECT_VERSION_PATCH 1)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Library for interacting with the encoders on the University of Manitoba Robotics Team's robotic arm"
        CACHE STRING "Package description for the package metadata"
        )
set(CPACK_PACKAGE_VENDOR "University of Manitoba Robotics Team")

set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
SET(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/output-packages")
set(CPACK_PACKAGING_INSTALL_PREFIX "/opt/${PROJECT_NAME}")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${MAINTAINER_NAME}")
set(CPACK_PACKAGE_CONTACT "${MAINTAINER_EMAIL}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)

set(CPACK_COMPONENTS_GROUPING ALL_COMPONENTS_IN_ONE)
set(CPACK_DEB_COMPONENT_INSTALL YES)
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

include(CPack)