FROM ros:humble

RUN apt update && apt install -y \
	ros-humble-rviz2 \
	ros-humble-demo-nodes-cpp \
	ros-humble-demo-nodes-py \
	ros-humble-xacro \
	ros-humble-joint-state-publisher-gui \
	ros-humble-teleop-twist-keyboard \
	ros-humble-ros2-control \
	ros-humble-ros2-controllers \
	vim \
	htop \
	xterm

WORKDIR /workspace

CMD ["/bin/bash"]
