ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}
COPY requirements.txt /opt/app/requirements.txt
LABEL authors="Syed Abraham Ahmed, Nikolaus Reichert, Alessandro Potenza"

# Environment Variables
ENV WS=/workspace

# Humble Stuff
RUN apt update && apt install -y \
	ros-humble-rviz2 \
	ros-humble-demo-nodes-cpp \
	ros-humble-demo-nodes-py \
	ros-humble-xacro \
	ros-humble-joint-state-publisher-gui \
	ros-humble-gazebo-ros-pkgs \
	ros-humble-teleop-twist-keyboard \
	ros-humble-ros2-control \
	ros-humble-ros2-controllers \
	ros-humble-gazebo-ros2-control \
# Humble - Camera Stuff
	ros-humble-vision-msgs \
	ros-humble-depthai \
	ros-humble-camera-calibration \
	ros-humble-image-transport-plugins \
	ros-humble-image-pipeline \
	ros-humble-diagnostic-updater \
	ros-humble-depth-image-proc \
	ros-humble-foxglove-msgs \
	ros-humble-rviz-imu-plugin

# ROS2 Dependancies
RUN apt update && apt install -y --no-install-recommends \
	vim \
	htop \
	xterm \
	python3 \
	python3-pip \
	build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-vcstool \
    wget \
	libusb-1.0-0-dev \
	libcairo2-dev \
	libgirepository1.0-dev \
    && rm -rf /var/lib/apt/lists/*

# Setup
RUN pip install -r /opt/app/requirements.txt

WORKDIR /workspace
CMD ["/bin/bash"]
