ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}

# Humble Stuff
RUN apt update && apt install -y \
	ros-humble-rviz2 \
	ros-humble-demo-nodes-cpp \
	ros-humble-demo-nodes-py \
	ros-humble-xacro \
	ros-humble-joint-state-publisher-gui \
	ros-humble-gazebo-ros-pkgs \
	ros-humble-teleop-twist-keyboard \
	ros-humble-ros2-control \
	ros-humble-ros2-controllers \
	ros-humble-gazebo-ros2-control 

# ROS2 Dependancies
RUN apt update && apt install -y \
	vim \
	htop \
	xterm \
	python3 \
	build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-vcstool \
    wget \
    && rm -rf /var/lib/apt/lists/*
	
	

WORKDIR /workspace
# ENTRYPOINT [""] TODO: Set Entrypoint for DEV
CMD ["/bin/bash"]
