controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    diff_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_controller:
  ros__parameters:
    # This is throttled by controller_manager's update_rate.
    publish_rate: 50.0
    base_frame_id: base_link

    left_wheel_names: ['left_front_wheel_joint', 'left_back_wheel_joint']
    right_wheel_names: ['right_front_wheel_joint', 'right_back_wheel_joint']

    # From gazebo_control.xacro.
    wheel_separation: 0.35
    wheel_radius: 0.05

    # A diff_drive thing for a later time. TODO
    use_stamped_vel: false
